# General settings
title: "Subhashisa Swain"
description: "Personal Website of Dr. Subhashisa Swain"
baseurl: ""  # If your site is hosted at a subpath, set it here (e.g., "/cv").
url: "https://subhashisa.github.io"  # Your GitHub Pages URL

# Theme settings
remote_theme: jekyll-theme-hyde  # Using a remote theme (jekyll-theme-hyde)

# Markdown and HTML settings for content pages
markdown: kramdown
highlighter: rogue

# Permalink settings (for URLs of individual pages)
permalink: /:title/

# Social links (for your social media)
social_links:
  github: "https://github.com/Subhashisa"   # Replace with your actual GitHub profile link
  linkedin: "https://uk.linkedin.com/in/subhashisa-swain-44779623"  # Replace with your LinkedIn profile link
  twitter: "https://twitter.com/Sw_Subhashis"  # Replace with your Twitter handle
  researchgate: "https://www.researchgate.net/profile/Subhashisa-Swain"  # Replace with your ResearchGate
  orcid: "https://orcid.org/0000-0001-9207-1065"  # Replace with your ORCID profile link

# Sass settings to use custom CSS file (if needed)
sass:
  sass_dir: assets/css
  style: compressed

# Include custom styles
include:
  - "_assets"

# Exclude unnecessary files
exclude:
  - "README.md"
  - "LICENSE"
